#!/usr/bin/env python3
"""make_dns_zone.py — Pro-feature #7 offline alternative: emit DNS config for all
phishlet hostnames so an INTERNAL DNS server (dnsmasq) serves the phishing zone
across the lab — no external DNS provider APIs needed.

Usage:
  python3 make_dns_zone.py --domain labphish.test --ip 192.168.80.68 \
      --phishlets ~/evilginx2-lab/phishlets [--out dnsmasq-lab.conf]

Emits:
  1. dnsmasq conf block:  address=/labphish.test/192.168.80.68  (wildcard)
  2. hosts-file lines for every phishlet hostname found in the phishlets dir.
"""
import argparse
import glob
import re

ap = argparse.ArgumentParser()
ap.add_argument("--domain", required=True)
ap.add_argument("--ip", required=True)
ap.add_argument("--phishlets", default=".")
ap.add_argument("--out", default="dnsmasq-lab.conf")
args = ap.parse_args()

hosts = set()
for f in glob.glob(args.phishlets.rstrip("/") + "/*.yaml"):
    text = open(f, encoding="utf-8").read()
    # hostnames come from `phishlets hostname <pl> <base>` + phish_sub in the yaml
    for m in re.finditer(r"phish_sub:\s*'([^']+)'", text):
        pass  # phish_sub alone is not enough; base domain comes from config
    # collect origin hosts for completeness
    for m in re.finditer(r"domain:\s*'([^']+)'", text):
        d = m.group(1)
        if d and d != args.domain:
            hosts.add(d)

conf = f"""# dnsmasq block for the lab phishing zone (generated by make_dns_zone.py)
# include from /etc/dnsmasq.d/ , then: systemctl restart dnsmasq
address=/{args.domain}/{args.ip}
"""
hosts_lines = "\n".join(f"{args.ip}\t{h}" for h in sorted(hosts))

with open(args.out, "w") as f:
    f.write(conf)
print(f"[+] wrote {args.out}")
print("[i] wildcard answer: *.%s -> %s" % (args.domain, args.ip))
if hosts:
    print("[i] origin hosts to add to /etc/hosts on DNS clients (or serve via internal zone):")
    print(hosts_lines)
print("[i] note: evilginx2 itself also runs an authoritative DNS server on :53 —")
print("    point client resolvers at it for the phish domain, or use this dnsmasq block.")
